language: minimal

services:
  - docker

cache:
  directories:
    - .build

before_script:
  - chown --recursive travis:travis .build && rmdir --ignore-fail-on-non-empty .build

script:
  - >-
    make all
    USE_DOCKER=1
    POST_GENERATE='git diff --exit-code'
    POST_FMT='git diff --exit-code'
    GO_TEST_FLAGS='-race -coverprofile=coverage.txt'
  - >-
    make test
    USE_DOCKER=1
    COMPOSE_FILE=docker-compose.override.yml
    GO_TEST_FLAGS='-tags integration_test'

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt -X fix
